config/routes.rb
Rails.application.routes.draw do
  get 'pages/splash'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#splash'
  get '/categories', to: 'categories#index', as: 'categories'
  resources :categories do
    resources :payments
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :payments
  validates :name, presence: true

  def total_amount
    payments.sum(:amount)
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :categories, dependent: :destroy
  has_many :payments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |u|
      u.permit(:email, :encrypted_password)
    end
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
  end

  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def splash; end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_category
  before_action :authenticate_user!

  def index; end

  def new
    @current_user = current_user
    @payment = Payment.new
    @categories = current_user.categories
  end

  def create
    @current_user = current_user
    @category = Category.find(params[:category_id])
    @payment = Payment.new(payment_params)
    @payment.user = @current_user
    @payment.category_id = @category.id

    if @payment.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def destroy
    @payment = Payment.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to category_path(@category), notice: 'payment deleted successfully' }
    end
  end

  private

  def set_category
    @category = current_user.categories.find(params[:category_id])
  end

  def payment_params
    params.require(:payment).permit(:name, :amount, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/categories/index.html.erb
<section class="categories-container">
  <div class="categories-header">
      <div class ="exit">
      <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'delete-btn' %>
       </div>
      <h2>CATEGORIES</h2>
      <div class ="search">
        <%= image_tag "search.png", alt: "Search Icon", class: "search-img"%>
      </div>
  </div>
  
  <ul class="categories">
 
  <% @categories.each do |category| %>
    <% if user_signed_in? && category.user_id == current_user.id %>
     <li class="category-container">
     <div class="cat-icon">
     <%= image_tag category.icon, alt: "category Icon", class: "cat-image"%>
     </div>
        <div class="cat-info-cont">
            <h3>
                <%= link_to category.name, category_path(category),  class: "category-name" %>
            </h3>
            <hr class="space">
            <p class="category-updated">
                 <%= category.updated_at.strftime('%d %b %Y')%>
             </p>  
        </div>
            <p class="cat-amount">$<%= category.payments.sum(:amount) %></p>
            
     </li>
 <% end %>
 <% end %>
</ul>
<div class="new-cat-container">
 <%= link_to "ADD CATEGORY", new_category_path, class: "new-category" %>
</div>
 
</section>

app/views/categories/new.html.erb
<!-- app/views/categories/new.html.erb -->



<%= form_for @category do |f| %>
   <div class="new-category-header">
      <div class ="back-arrow">
        <%= link_to categories_path do %>
          <%= image_tag "back_arrow.png", alt: "Back Arrow", class: "back-arrow-img" %>
        <% end %>
      </div>
     <h1>New Category</h1>
      <%= f.submit "Create", class: "cat-button" %>
    </div>
    <div class="field-name-new-category">
    <h2 class="Add name">Add a Category name</h2>
      <%= f.text_field :name, autocomplete: "category name", placeholder: "Name", class: "login-field" %>
    </div>


<div class="field-name-new-category">
    <h2 class="Add name">Add a Category Icon Link</h2>
      <%= f.text_field :icon, class: "login-field" %>
    </div>
<% end %>

app/views/categories/show.html.erb
<section class="categories-container">
  <div class="categories-header">
    <div class ="back-arrow">
      <%= link_to categories_path do %>
        <%= image_tag "back_arrow.png", alt: "Back Arrow", class: "back-arrow-img" %>
      <% end %>
    </div>
    <h2>TRANSACTIONS</h2>
    <div class ="home">
    <%= link_to 'Home', categories_path, class: "Home" %>
    </div>
  </div>

  <div class="category-details-container">
    <div class="category-container">
      <div class="mov-icon">
        <%= image_tag @category.icon, alt: "category Icon", class: "movement-img"%>
      </div>
      <div class="cat-info-container">
        <h3 class="category-name"><%= @category.name %></h3>
        <hr class="space">
      </div>
      <div class="value">
         <p class="total">TOTAL</p>
         <p class="cat-amount">$<%= @category.payments.sum(:amount) %></p>
      </div>
    </div>
    
    <div class="entities-container">
      <% @category.payments.order(created_at: :desc).each do |payment| %>
        <div class="mov-container">
          <p class="mov-name"><%= payment.name %></p>
          <hr class="mov-space">
          <p class="mov-value">$ <%= payment.amount %></p>
          <%= link_to "X", category_payment_path(@category, payment), class: "delete-mov", method: :delete, data: { turbo_confirm: "Are you sure?" } %>
        </div>
      <% end %>
    </div>
    <div class="new-mov-container">
      <%= link_to "ADD A MOVEMENT", new_category_payment_path(@category), class: "new-mov" %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PennyWisePal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <link href="https://fonts.googleapis.com/css?family=Proxima+Nova:400,600,700&display=swap" rel="stylesheet">
  </head>

  <body>
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/splash.html.erb
  <div class="splash">
     <%= image_tag '/logo.png', class: 'logo' %>
    <p>Welcome to Your PennyWisePal! Please sign up or log in to get started:</p>
    <div class="splash-buttons-container">
      <%= button_to "Sign up", new_user_registration_path,  method: :get, class: "splash-button" %>
      <%= button_to "Log in", new_user_session_path, class: "splash-button" %>
    </div>
  </div>

app/views/payments/new.html.erb
<%= form_with model: @payment, url: category_payments_path(@category), method: :post, local: true, html: { class: "new-entity-form" } do |f| %>
  <div class="new-entity-header">
    <div class ="back-arrow">
      <%= link_to category_path(@category) do %>
        <%= image_tag "back_arrow.png", alt: "Back Arrow", class: "back-arrow-img" %>
      <% end %>
    </div>
    <h2>ADD PAYMENT</h2>
    <%= f.submit "ADD", class: "submit-new-mov" %>
  </div>
  <div class = "new-mov-body">
    <div class="entry-field">
      <%= f.text_field :name, autocomplete: "Name", placeholder: "Name", class: "login-field" %>
    </div>
    <div class="entry-field">
      <%= f.text_field :amount, autocomplete: "Amount", placeholder: "Amount", class: "login-field" %>
    </div>
    <div class="entry-field">
      <% @categories.each do |category| %>
        <p><%= check_box_tag 'payment[category_ids][]', category.id, @payment.categories.include?(category), multiple: true %><%= category.name %></p>
       <% end %>
    </div>
  </div>
<% end %>